# Generated by Django 5.2.17 on 2026-08-20 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_membership_id",
                    models.PositiveBigIntegerField(
                        db_index=True,
                        help_text="accounts.Membership id of the student's STUDENT membership. A bare id and not a ForeignKey — see the comment above and docs/tenancy.md.",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        help_text="The student's name as it stood when this entry was posted.",
                        max_length=255,
                    ),
                ),
                (
                    "student_reference",
                    models.CharField(
                        blank=True,
                        help_text="Admission number as it stood when this entry was posted.",
                        max_length=64,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("payment", "Payment"),
                            ("discount", "Discount"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount_kobo",
                    models.BigIntegerField(
                        help_text="Whole kobo. Positive increases what the family owes; negative reduces it. Never a float, never naira."
                    ),
                ),
                (
                    "narration",
                    models.CharField(
                        help_text="What this line is for, in the school's words.",
                        max_length=255,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("effective_on", models.DateField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="accounts.User id of whoever posted this, where there was one.",
                        null=True,
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        help_text="For a REVERSAL, the entry being undone. Null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="fees.feeledgerentry",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="The term this entry is reckoned against.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_entries",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "fee ledger entries",
                "ordering": ["-effective_on", "-id"],
                "indexes": [
                    models.Index(
                        fields=["student_membership_id", "term"],
                        name="fees_feeled_student_b18553_idx",
                    ),
                    models.Index(
                        fields=["term", "kind"], name="fees_feeled_term_id_ece94f_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_kobo", 0), _negated=True),
                        name="a_ledger_entry_moves_money",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "charge"), _negated=True),
                            ("amount_kobo__gt", 0),
                            _connector="OR",
                        ),
                        name="a_charge_increases_what_is_owed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind__in", ("payment", "discount")), _negated=True
                            ),
                            ("amount_kobo__lt", 0),
                            _connector="OR",
                        ),
                        name="a_payment_or_discount_reduces_what_is_owed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "reversal"), ("reverses__isnull", False)),
                            models.Q(
                                models.Q(("kind", "reversal"), _negated=True),
                                ("reverses__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="only_a_reversal_names_what_it_undoes",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reverses__isnull", False)),
                        fields=("reverses",),
                        name="an_entry_is_reversed_at_most_once",
                    ),
                ],
            },
        ),
    ]
