# Generated by Django 5.2.17 on 2026-08-17 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Stable sign-in handle. Staff and parents usually get their email; students get a school-issued handle such as STM/2026/0042.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_platform_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "School administrator"),
                            ("principal", "Principal"),
                            ("teacher", "Teacher"),
                            ("bursar", "Bursar"),
                            ("parent", "Parent or guardian"),
                            ("student", "Student"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("ended", "Ended"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=64)),
                (
                    "started_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("ended_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["school__name", "role", "user__full_name"],
            },
        ),
        migrations.CreateModel(
            name="Guardianship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        default="guardian",
                        max_length=16,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=False)),
                ("receives_invoices", models.BooleanField(default=True)),
                (
                    "can_collect",
                    models.BooleanField(
                        default=True, help_text="Authorised for pickup."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardianships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The child's STUDENT membership, which pins the school too.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardianships",
                        to="accounts.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["student__user__full_name"],
            },
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["school", "role", "status"],
                name="accounts_me_school__d47c20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "role"], name="accounts_me_user_id_82b08b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["school", "reference"], name="accounts_me_school__e7d53e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "school", "role"),
                name="uniq_membership_user_school_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("role", "student"), models.Q(("status", "ended"), _negated=True)
                ),
                fields=("user",),
                name="one_live_student_membership_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianship",
            constraint=models.UniqueConstraint(
                fields=("guardian", "student"),
                name="uniq_guardianship_guardian_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_contact", True)),
                fields=("student",),
                name="one_primary_contact_per_student",
            ),
        ),
    ]
