# Generated by Django 5.2.17 on 2026-08-17 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardianship",
            name="guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardianships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="guardianship",
            name="student",
            field=models.ForeignKey(
                help_text="The child's STUDENT membership, which pins the school too.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardianships",
                to="accounts.membership",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="schools.school",
            ),
        ),
    ]
