# Generated by Django 5.2.17 on 2026-08-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_guardianship_guardian_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Stable sign-in handle. Staff and parents usually get their email; students get a school-issued handle such as STM/2026/0042. A username that is itself a phone number is stored in E.164, matching the phone field.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
