# Generated by Django 5.2.17 on 2026-08-19 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_username"),
        ("schools", "0002_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_side",
                    models.CharField(
                        choices=[
                            ("releasing", "Releasing school"),
                            ("receiving", "Receiving school"),
                        ],
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Free text, shown to both schools."
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_answered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The child's STUDENT membership, which pins the leaving school too.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests",
                        to="accounts.membership",
                    ),
                ),
                (
                    "to_school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfer_requests",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["to_school", "status"],
                        name="accounts_tr_to_scho_5e87db_idx",
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="accounts_tr_student_bf5ae9_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("student",),
                        name="one_pending_transfer_request_per_student",
                    )
                ],
            },
        ),
    ]
