# Generated by Django 5.2.17 on 2026-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_transferrequest"),
        ("schools", "0002_invitation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transferrequest",
            old_name="answered_at",
            new_name="resolved_at",
        ),
        migrations.RenameField(
            model_name="transferrequest",
            old_name="answered_by",
            new_name="resolved_by",
        ),
        migrations.AddField(
            model_name="transferrequest",
            name="route",
            field=models.CharField(
                choices=[
                    ("handshake", "Agreed between two schools"),
                    ("single_party", "Carried out by one authority"),
                ],
                default="handshake",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="transferrequest",
            name="requested_side",
            field=models.CharField(
                blank=True,
                choices=[
                    ("releasing", "Releasing school"),
                    ("receiving", "Receiving school"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="transferrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("route", "single_party"),
                    ("status__in", ["pending", "withdrawn"]),
                    models.Q(
                        ("resolved_by__isnull", False),
                        models.Q(
                            ("requested_by", models.F("resolved_by")), _negated=True
                        ),
                    ),
                    _connector="OR",
                ),
                name="answered_transfer_names_two_signatories",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("route", "handshake"),
                    models.Q(
                        ("resolved_by__isnull", False),
                        ("requested_by", models.F("resolved_by")),
                    ),
                    _connector="OR",
                ),
                name="single_party_transfer_names_one_signatory",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("route", "handshake"), ("status", "accepted"), _connector="OR"
                ),
                name="single_party_transfer_is_always_accepted",
            ),
        ),
        migrations.AddConstraint(
            model_name="transferrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("requested_side__isnull", False), ("route", "handshake")),
                    models.Q(
                        ("requested_side__isnull", True), ("route", "single_party")
                    ),
                    _connector="OR",
                ),
                name="transfer_side_matches_route",
            ),
        ),
    ]
