# Generated by Django 5.2.17 on 2026-08-21 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_answered_at_transferrequest_resolved_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignInAttempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("identifier", "Identifier"),
                            ("address", "Network address"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="SHA-256 of the normalized identifier, or the address itself.",
                        max_length=255,
                    ),
                ),
                ("failures", models.PositiveIntegerField(default=0)),
                (
                    "window_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key"), name="one_signin_counter_per_key"
                    )
                ],
            },
        ),
    ]
