# Generated by Django 5.2.17 on 2026-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_signinattempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "School administrator"),
                    ("principal", "Principal"),
                    ("vp_academic", "Vice Principal (Academic)"),
                    ("teacher", "Teacher"),
                    ("bursar", "Bursar"),
                    ("parent", "Parent or guardian"),
                    ("student", "Student"),
                ],
                max_length=16,
            ),
        ),
    ]
