# Generated by Django 5.2.17 on 2026-08-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=16)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="A subject no longer taught. Kept, because old scores name it.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="uniq_subject_code"),
                    models.UniqueConstraint(fields=("name",), name="uniq_subject_name"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "First CA", "Exam".', max_length=64
                    ),
                ),
                ("max_score", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="academics.term",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="gradebook.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["term", "subject__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_membership_id",
                    models.PositiveBigIntegerField(db_index=True),
                ),
                ("value", models.PositiveSmallIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "recorded_by_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "updated_by_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="gradebook.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment", "student_membership_id"],
                "indexes": [
                    models.Index(
                        fields=["assessment", "student_membership_id"],
                        name="gradebook_s_assessm_299286_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment", "student_membership_id"),
                        name="one_score_per_student_per_assessment",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("term", "subject", "name"),
                name="uniq_assessment_term_subject_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_score__gte", 1)),
                name="an_assessment_is_worth_at_least_one_mark",
            ),
        ),
    ]
