# Generated by Django 5.2.17 on 2026-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        help_text="Academic session this term belongs to, e.g. 2025/2026.",
                        max_length=9,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("first", "First term"),
                            ("second", "Second term"),
                            ("third", "Third term"),
                        ],
                        max_length=16,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-session", "starts_on"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "name"), name="uniq_term_session_name"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="one_current_term",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_on__gt", models.F("starts_on"))),
                        name="term_ends_after_it_starts",
                    ),
                ],
            },
        ),
    ]
