# Generated by Django 5.2.17 on 2026-08-20 11:05

import academics.models
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="next_term_starts_on",
            field=models.DateField(
                blank=True,
                help_text="When the next term begins, as announced during this one. Blank until the school says.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="school_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Teaching days in this term, as the school counts them. The denominator of every attendance figure.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("next_term_starts_on__isnull", True),
                    ("next_term_starts_on__gt", models.F("ends_on")),
                    _connector="OR",
                ),
                name="next_term_starts_after_this_one_ends",
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("school_days__isnull", True),
                    (
                        "school_days__lte",
                        django.db.models.expressions.CombinedExpression(
                            academics.models.DaysBetween(
                                models.F("ends_on"), models.F("starts_on")
                            ),
                            "+",
                            models.Value(1),
                        ),
                    ),
                    _connector="OR",
                ),
                name="school_days_fit_inside_the_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("school_days__isnull", True),
                    ("school_days__gte", 1),
                    _connector="OR",
                ),
                name="a_term_has_at_least_one_school_day",
            ),
        ),
    ]
