# Generated by Django 5.2.17 on 2026-08-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_term_next_term_starts_on_term_school_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="The school's own ordering, smallest first. Arms of one year share a level.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="A group no longer taught. Kept, because old placements name it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["level", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="uniq_class_group_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_membership_id",
                    models.PositiveBigIntegerField(db_index=True),
                ),
                ("placed_by_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="academics.classgroup",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="academics.term",
                    ),
                ),
            ],
            options={
                "ordering": ["class_group", "student_membership_id"],
                "indexes": [
                    models.Index(
                        fields=["class_group", "term"],
                        name="academics_c_class_g_c4128f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term", "student_membership_id"),
                        name="one_class_placement_per_student_per_term",
                    )
                ],
            },
        ),
    ]
